<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="TableSchemaPerform.aspx.cs" Inherits="TableOnBoardingV2.TableSchemaPerform" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <asp:GridView ID="SchemaContent" runat="server" CellPadding="4" ForeColor="#333333" DataKeyNames="TableHeader"
            onrowediting="SchemaContent_RowEditing" OnRowDeleting="SchemaContent_RowDeleting" OnRowCancelingEdit="SchemaContent_RowCancelingEdit" OnRowUpdating="SchemaContent_RowUpdating" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true">
            <FooterStyle BackColor="#990000" Font-Bold="true" ForeColor="White" />
            <Columns>
                <asp:BoundField DataField="TableHeader" HeaderText="TableHeader" ReadOnly="true" />
                <asp:TemplateField HeaderText="IsSubject">
                    <ItemTemplate>
                        <asp:DropDownList ID="DropDownList_IsSubject" runat="server">
                            <asp:ListItem Value="2">true</asp:ListItem>
                            <asp:ListItem Selected="True" Value="1">false</asp:ListItem>
                        </asp:DropDownList>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="Schema" HeaderText ="Schema" />
                <asp:TemplateField HeaderText="Type">
                    <ItemTemplate>
                        <asp:DropDownList ID="DropDownList_Type" runat="server"> 
                            <asp:ListItem>String</asp:ListItem>
                            <asp:ListItem>Bool</asp:ListItem>
                            <asp:ListItem>Numeric</asp:ListItem>
                        </asp:DropDownList>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="NeedIndex">
                    <ItemTemplate>
                        <asp:DropDownList ID="DropDownList_NeedIndex" runat="server">
                            <asp:ListItem Selected="True" Value="True">true</asp:ListItem>
                            <asp:ListItem Value="False">false</asp:ListItem>
                        </asp:DropDownList>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField ="RegexForValue" HeaderText="RegexForValue" />
                <asp:TemplateField HeaderText ="NL">
                    <EditItemTemplate>
                        <asp:TextBox ID="Nl_TextBox" runat="server">
                        </asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <%-- <asp:BoundFielg DataField="NL" HeaderText="NL" /> --%>
                <%-- <asp:CommandField HeaderText="EditSchema" UpdateText="Save" CancelText="Cancle" DeleteText="Delete" ShowDeleteButton="true" ShowCancelButton="true" ShowEditButton="true" EditText="Edit" /> --%>
            </Columns>
            <RowStyle ForeColor="#000066" />
            <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
            <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
        </asp:GridView>
        <asp:Button ID="AddNewRow" runat="server" Text="Add New Row" OnClick="AddNewRow_Click" />
    </form>
</body>
</html>